// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"backend-go/config"
	"backend-go/internal/api"
	"backend-go/internal/handlers"
	"backend-go/internal/repository"
	"backend-go/internal/services"

	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"gorm.io/gorm"

	_ "backend-go/docs"
)

// Injectors from wire.go:

func InitializeAPI() (*gin.Engine, error) {
	db := ProvideDB()
	userRepository := repository.NewUserRepository(db)
	cacheService := services.NewCacheService()
	authService := services.NewAuthService(userRepository, cacheService)
	authHandler := handlers.NewAuthHandler(authService)
	santriRepository := repository.NewSantriRepository(db)
	psbService := services.NewPSBService(santriRepository)
	psbHandler := handlers.NewPSBHandler(psbService)
	articleRepository := repository.NewArticleRepository(db)
	articleService := services.NewArticleService(articleRepository, cacheService)
	articleHandler := handlers.NewArticleHandler(articleService)
	mediaService, err := services.NewMediaService()
	if err != nil {
		return nil, err
	}
	mediaHandler := handlers.NewMediaHandler(mediaService)
	dashboardService := services.NewDashboardService(santriRepository, articleRepository, userRepository)
	dashboardHandler := handlers.NewDashboardHandler(dashboardService)
	galleryRepository := repository.NewGalleryRepository(db)
	galleryService := services.NewGalleryService(galleryRepository, mediaService)
	galleryHandler := handlers.NewGalleryHandler(galleryService)
	messageRepository := repository.NewMessageRepository(db)
	messageService := services.NewMessageService(messageRepository)
	messageHandler := handlers.NewMessageHandler(messageService)
	videoRepository := repository.NewVideoRepository(db)
	videoService := services.NewVideoService(videoRepository)
	videoHandler := handlers.NewVideoHandler(videoService)
	achievementRepository := repository.NewAchievementRepository(db)
	achievementService := services.NewAchievementService(achievementRepository)
	achievementHandler := handlers.NewAchievementHandler(achievementService)
	healthHandler := handlers.NewHealthHandler()
	apiHandlers := api.Handlers{
		AuthHandler:        authHandler,
		PSBHandler:         psbHandler,
		ArticleHandler:     articleHandler,
		MediaHandler:       mediaHandler,
		DashboardHandler:   dashboardHandler,
		GalleryHandler:     galleryHandler,
		MessageHandler:     messageHandler,
		VideoHandler:       videoHandler,
		AchievementHandler: achievementHandler,
		HealthHandler:      healthHandler,
	}
	engine := api.NewRouter(apiHandlers)
	return engine, nil
}

// wire.go:

func ProvideDB() *gorm.DB {
	return config.DB
}

var repositorySet = wire.NewSet(
	ProvideDB, repository.NewUserRepository, repository.NewSantriRepository, repository.NewArticleRepository, repository.NewGalleryRepository, repository.NewMessageRepository,
)

var serviceSet = wire.NewSet(services.NewMediaService, services.NewCacheService, services.NewAuthService, services.NewPSBService, services.NewArticleService, services.NewDashboardService, services.NewGalleryService, services.NewMessageService)

var handlerSet = wire.NewSet(handlers.NewAuthHandler, handlers.NewPSBHandler, handlers.NewArticleHandler, handlers.NewMediaHandler, handlers.NewDashboardHandler, handlers.NewGalleryHandler, handlers.NewMessageHandler)
